### ISSUE TITLE
Installing Quay README.md - bad oc command

### ISSUE THREAD

**Issue by dwojciec** [RedHatWorkshops/quay-on-openshift#1]
the correct command is 
oc adm policy add-scc-to-user anyuid system:serviceaccount:quay-enterprise-serviceaccount:default
and not 
oc adm policy add-scc-to-user anyuid system:serviceaccount:quay-enterpriseefault

**Comment by christianh814** [comment]
Fixed  by commit #7b3d9a9

**Comment by christianh814** [comment]
Fixed  by commit 7b3d9a9
